# Nombre del workflow
name: Deploy Vite Project to GitHub Pages

# Se ejecuta cada vez que haces un push a la rama "main"
on:
  push:
    branches: [ "main" ]

# Permite que el workflow se cancele si haces un nuevo push rápidamente
concurrency:
  group: "pages"
  cancel-in-progress: true

# Permisos necesarios para el despliegue
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Job para construir el proyecto
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          # La línea 'cache: npm' ha sido eliminada de aquí
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  # Job para desplegar el proyecto
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
